### ISSUE TITLE
defaultproperties not properly assigned?

### ISSUE THREAD

**Issue by robojumper** [thraaawn/BlackmarketUsage#1]
UIAddToBlackmarket.uc

```
defaultproperties {
    ScreenClass = class'UIBlackMarket_Sell';
}
```

The opening brace must be on a new line. However, if you fix it that way, it won't work with Grimy's Loot Mod. I suggest the following:

```
event OnInit(UIScreen Screen) {
    if (UIBlackMarket_Sell(Screen) != none) {
        Maketh(UIBlackMarket_Sell(Screen));
    }
}

Event OnReceiveFocus(UIScreen Screen) { 
    if (UIBlackMarket_Sell(Screen) != none) {
        Maketh(UIBlackMarket_Sell(Screen));
    }

} 
// ...
defaultproperties
{
    ScreenClass = none
}
```

This way, it will retain compatibility (and also get rid of the hundreds of Accessed none: 'screen' messages your mod throws).

**Comment by davenonymous** [comment]
Implemented as suggested. Thanks!
