### ISSUE TITLE
The text "foobar" is displayed for some reason

### ISSUE THREAD

**Issue by BlueRaja** [thraaawn/BlackmarketUsage#4]
For some reason the version of the mod on Steam Workshop has [this line](https://github.com/thraaawn/BlackmarketUsage/blob/master/Src/BlackmarketUsage/Classes/UIAddToBlackmarket.uc#L4)...

```
`define coloredtext(text, color) "<font color='#"$`color$"'>"$`text$"</font>"
```

..looking like this:

```
`define coloredtext(text, color) "<font color='#"$`color$"'>"$`text$"foobar</font>"
```

(Zyxpsilon tracked this one down)

**Comment by davenonymous** [comment]
Oupsi, I somehow uploaded the version with some debug lines in it.
Fixed.
